### ISSUE TITLE
2.6 cuda 10.1: x16rv2 on NH and xevan on zegpool

### ISSUE THREAD

**Issue by Quake4** [zealot-rvn/z-enemy#1] opened 2020-05-14 09:41 UTC
![image](https://user-images.githubusercontent.com/29517243/81919197-31446400-95e0-11ea-8525-0a234c45cc8b.png)
![image](https://user-images.githubusercontent.com/29517243/81920497-f2171280-95e1-11ea-9161-570f44ca5728.png)

**Comment by RainbowMiner** [comment] 2020-05-14 12:30
Confirmed. I happen to have problems with hex mining, as well.

**Comment by RainbowMiner** [comment] 2020-05-14 13:44
Seems to be fixed in v2.6.1 - thank you for the quick update!

**Closed as completed** 2020-05-14 13:51 UTC
